### ISSUE TITLE
[Review Sprint1] Inteface is not correclty referenced for test class

### ISSUE THREAD

**Issue by NicolasGlassey** [CPNV-ES/VIR-PY-DWAQ#1]
//TODO must be documented

**Comment by NicolasGlassey** [comment]
@SuperQuentin 

Andi s'était annoncé pour prendre cette tâche... et là je vois que vous vous êtes auto-assigné le travail... Tout va bien ? Pourquoi ce changement ?

**Comment by SuperQuentin** [comment]
Je me suis assigné la tâche après avoir discuté avec andi, j'avais déjà une solution et travaillant sur la réparation des tests unitaires cela impactait également cette tache. il me semble aussi que vous l'aviez assigné à cette tâche quand vous l'avez crée en mentionnant que l'on pourrait changer son assignement par la suite. je tâcherai à l'avenir si un changement d'assignement de préciser la raison

**Comment by WilliamWHN** [comment]
Has been patch by @SuperQuentin
