### ISSUE TITLE
Boto3 UnitTest SocketWarning

### ISSUE THREAD

**Issue by dylanramos** [CPNV-ES/VIR-PY-DWAQ#2]
https://github.com/psf/requests/issues/3912
https://imgur.com/a/DiM8mP9

Trouver une solution pour résoudre les warnings
Documenter pour les prochains dévs
Backlog de boto3

**Comment by SuperQuentin** [comment]
https://boto3.amazonaws.com/v1/documentation/api/latest/reference/core/session.html#boto3.session.Session.client

il faut passé False à la propriété use_ssl lors de l'instanciation du client, on peut aussi passé différent autre information notamment tous ce qui est aws access key, location ect...

**Comment by SuperQuentin** [comment]
Le problème a été résolu mais il reste des soucis de tracealloc
